name: pipeline

on:
  push:
    branchs: [main]

jobs:
  starter:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v3
      - name: Install
        run: npm install
      - name: run lint
        run: npm run lint
